// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkztrkwlaU170TBgx33Jm5-soTOyTOusg',
    appId: '1:136001590052:android:d6b04d870792e6336059b1',
    messagingSenderId: '136001590052',
    projectId: 'car-wash-lighting',
    databaseURL: 'https://car-wash-lighting-default-rtdb.firebaseio.com',
    storageBucket: 'car-wash-lighting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT1RFXpLSno3XVLlc2QW3F-qjhblkl_eA',
    appId: '1:136001590052:ios:6d78f4798f8623626059b1',
    messagingSenderId: '136001590052',
    projectId: 'car-wash-lighting',
    databaseURL: 'https://car-wash-lighting-default-rtdb.firebaseio.com',
    storageBucket: 'car-wash-lighting.appspot.com',
    androidClientId: '136001590052-ckturnc7ks5npj61ums0o2gkdom2kaqa.apps.googleusercontent.com',
    iosClientId: '136001590052-sd3r7uoedib4deo6vterhl6lkdusk77v.apps.googleusercontent.com',
    iosBundleId: 'com.carwash.user',
  );
}
